### ISSUE TITLE
mistaken assumption that HTTP POST endpoints are required

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ets-wcs11#15]
The test ""wcs:GetCapabilities_Response_OperationsMetadata_Post_Multiple_Connect_Points" seems to assume that a WCS 1.1.1 service must have HTTP POST endpoints to be conformant.  However, OGC 07-067r2 Subclause 8.3.2.2 makes no such statement.  It states that *if* a service has HTTP POST endpoints, then the encoding of each of these endpoints must be declared.  As far as I can tell, it's perfectly legal to have a WCS 1.1.1 service with only HTTP GET endpoints.

**Comment by bermud** [comment]
@pomakis, we will look at your question soon. Thank you for reporting.

**Comment by dstenger** [comment]
If no "PostEncoding" Constraint is included in the capabilities, HTTP POST should not be tested in "wcs:GetCapabilities_Response_OperationsMetadata_Post_Multiple_Connect_Points".

Can you please provide a test service to analyse the issue more in detail?

**Comment by pomakis** [comment]
https://demo.cubewerx.com/cubewerx/cubeserv/simple?DATASTORE=Foundation&SERVICE=WCS&REQUEST=GetCapabilities&VERSION=1.1.1

**Comment by dstenger** [comment]
You are right, the test fails as the GetCapabilities operation does not offer an POST DCP URL in the capabilities.

We will do further investigation.

**Comment by dstenger** [comment]
Chapter 8.2.1 in WCS 1.1.1 specification states following:

"All WCS servers shall implement HTTP GET transfer of the GetCapabilities operation
request, using KVP encoding. Servers may also implement HTTP POST transfer of the
GetCapabilities operation request, using XML encoding only."

So, the POST encoding is optional for GetCapabilities.
The test has to be adjusted to consider a possible missing POST encoding.

**Comment by dstenger** [comment]
A fix was created and is provided via pull request #17.
The fix will be part of the upcoming release.

**Comment by dstenger** [comment]
The pull request (#17) was tested successfully, merged to the master branch and will be part of the upcoming release.
