### ISSUE TITLE
The wcs:DescribeCoverage_MissingVersion test have a version parameter

### ISSUE THREAD

**Issue by matsoo** [opengeospatial/ets-wcs11#16]
The test assertion is that a request without a version parameter should generate a service exception, but the test includes a version parameter in the request. This makes the request valid and it then fails because the response is not a service exception.

**Comment by bermud** [comment]
@matsoo, thank you for reporting we will investigate.

**Comment by dstenger** [comment]
Yes, you are right, for GET requests a version parameter is added although the assertion says otherwise.

To fix this, the version parameter of the GET request has to be removed.

**Comment by dstenger** [comment]
A fix was created and is provided via pull request #18.
The fix will be part of the upcoming release.

**Comment by dstenger** [comment]
The pull request (#18) was tested successfully, merged to the master branch and will be part of the upcoming release.
