### ISSUE TITLE
xml:lang attribute not accepted in ExceptionReport element

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ets-wcs11#19]
When testing for a valid exception report (e.g., for test wcs:GetCapabilities_Sections_Bogus), an xml:lang attribute in the root <ExceptionReport> element causes the test to fail in the following way:

Request d1e4026_1:
   Method: GET
   URL: https://demo.cubewerx.com/cubewerx/cubeserv/simple?DATASTORE=Foundation&&service=WCS&request=GetCapabilities&version=1.1.1&sections=Bogus
   Response from parser ctlp:XMLValidatingParser:
      
   Messages from parser ctlp:XMLValidatingParser:
        Validation error:
  cvc-complex-type.3.2.2: Attribute 'xml:lang' is not allowed to appear in element 'ExceptionReport'.
1 validation error detected.

Message d1e4088_1:
   Parse error in test. Perhaps the response conforms to the wrong schema.

Result: Failed

However, xml:lang is a valid attribute in the OWS 1.1.0 schemas.

**Comment by dstenger** [comment]
Thank you for reporting the issue. We will do further investigation.

**Comment by dstenger** [comment]
The lang attribute definition is commented out in the schema which is used for validation of the response (ets-wcs11/src/main/resources/xsd/ogc/ows/1.1.0/owsExceptionReport.xsd).
We will investigate why this is the case and update the schema if necessary.

**Comment by dstenger** [comment]
Schema was updated in following pull request: #24. This solves the reported bug.

**Comment by dstenger** [comment]
The pull request was merged into the master branch and will be part of the upcoming release.
