### ISSUE TITLE
wcs:DescribeCoverage_MissingVersion doesn't test missing version

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ets-wcs11#22]
The wcs:DescribeCoverage_MissingVersion test is supposed to "verify that when a DescribeCoverage request with a missing version parameter is submitted, the response is valid XML that validates against the OWS Common 1.1.0 ExceptionReport schema".  However, it actually sends version=1.1.1 in the request, as is clear from the XML source code for the test.

**Comment by dstenger** [comment]
Thank you for reporting the issue.

This bug was already reported in #16 and has been fixed since version 1.8.
Can you please check if the error is still occurring in 1.8?

**Comment by bermud** [comment]
@pomakis, please let us know if you still have the issue, if not we will close it. Thank you!

**Comment by pomakis** [comment]
This particular issue seems to be fixed (despite the fact that http://cite.opengeospatial.org/teamengine/listings/srv_local_teamengine-prod_TE_BASE_scripts_wcs_1.1.1_ctl_wcs.html#wcs:DescribeCoverage_MissingVersion still seems to show that it includes a version parameter), so I guess it's okay to close it.  However, there's a more fundamental problem with the wcs:DescribeCoverage_MissingVersion test that perhaps I'll address by opening another issue.
