### ISSUE TITLE
Several tests fail as syntax for RangeSubset is erroneous

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wcs11#26]
Following tests fail:
- **GetCoverage_RangeSubset_InterpolationMethod**
- **GetCoverage_RangeSubset_Axis_Identifier_One_Key**
- **GetCoverage_RangeSubset_Axis_Identifier_Some_Keys**
- **GetCoverage_RangeSubset_Axis_Identifier_All_Keys**

In all cases whitespaces are included in the RangeSubset parameter.
E.g.:
- RangeSubset=Field_1:nearest linear cubic
- RangeSubset=Field_1[BAND[1 2 3]]

According to chapter "10.2.2.2 RangeSubset KVP syntax" (page 46) of the specification, whitespaces are not valid characters for delimiters.

In addition, regarding test **GetCoverage_RangeSubset_InterpolationMethod** it has to be checked why **linear** and **cubic** do not have a **FieldId**,

**Comment by dstenger** [comment]
**Analysis**

Unfortunately, the test service is not available any more. So results of analysis can not be verified.

**GetCoverage_RangeSubset_InterpolationMethod**

Following value is picked from DescribeCoverage response: ```CoverageDescriptions/CoverageDescriptionRange/Field/InterpolationMethods/InterpolationMethod```

Does the test server offer multiple methods in one InterpolationMethod element (e.g. ```<InterpolationMethod>nearest linear cubic</InterpolationMethod>```)?

For each interpolation method a new InterpolationMethod should be used (not multiple methods in one element).
This is described in chapter ```H.3.1 Interpolation methods contents``` (page 111) in the specification.

**GetCoverage_RangeSubset_Axis_Identifier_***

Regarding the three other failures the result of the analysis is similar.

Following value is picked from DescribeCoverage response: ```CoverageDescriptions/CoverageDescription/Range/Field/Axis/AvailableKeys/Key```

Does the test server offer multiple keys in one Key element (e.g. ```<Key>1 2 3</Key>```)?

For each interpolation method a new InterpolationMethod should be used (not multiple methods in one element).
This is described in chapter ```Table 19 — Parts of AvailableKeys data structure``` (page 32) in the specification.

**Comment by dstenger** [comment]
I just found a log of an old test session with the test server.

The element structure of the test server is correct.

So, the XPath expression of those tests has to be fixed.

To make verification of a potential fix possible: Can you please reactivate the test server?

**Comment by dstenger** [comment]
We are currently working on a fix.

Can you provide a service we can use for testing?

**Comment by dstenger** [comment]
We were able to test the fix successfully.
Pull request was created (#28) and will be merged right before the next release is built.

**Comment by dstenger** [comment]
The feature branch was tested successfully and was merged into master branch.
The fix will be part of the upcoming release.

**Comment by greatzzk** [comment]
@dstenger @lgoltz - 
what is the status of this issue? i am seeing regression bounced back in te2. it is still sending with whitespace as field deliminators.
![image](https://user-images.githubusercontent.com/11200872/88856619-a79d3f00-d1a9-11ea-8396-53c16993c9a3.png)

**Comment by dstenger** [comment]
This issue should already be fixed and installed on the Beta environment (https://cite.opengeospatial.org/te2/).

Can you please create a new issue if there are further problems?
Is it possible to provide a test service to reproduce the problem?

**Comment by greatzzk** [comment]
dirk, i did use the te2 env and saw this problem. i've created another issue for this one and attached the testing service in that issue. thanks.
https://github.com/opengeospatial/ets-wcs11/issues/65
