### ISSUE TITLE
Several tests fail due to a InvocationTargetException

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wcs11#27]
Following tests are failing:
- GetCoverage_RangeSubset_KVP_Syntax_Semicolon_Between_Field_Identifier_And_InterpolationMethod
- GetCoverage_RangeSubset_KVP_Syntax_Semicolon_Between_Axis_Identifiers
- GetCoverage_RangeSubset_KVP_Syntax_Semicolon_Between_Axis_Keys
- GetCoverage_RangeSubset_KVP_Syntax_Missing_Opening_Square_Bracket_Before_Axis_Identifier

Although the tested service returns an expected exception, following error is thrown by the test suite:

```
Error in call to extension function {public org.w3c.dom.NodeList com.occamlab.te.TECore.request(org.w3c.dom.Document,java.lang.String) throws java.lang.Throwable}: Exception in extension function java.lang.reflect.InvocationTargetException
```

**Comment by greatzzk** [comment]
Thank you. @bermud .
These tests also have problems like ones in: [https://github.com/opengeospatial/ets-wcs11/issues/26](url)

**Comment by dstenger** [comment]
You are right. There are used similar erroneous requests as in #26. These probably lead to the failure of the request method.
So, a fix for #26 should also solve this issue.

Nevertheless, the error message could be improved for that tests.

Is there a test service we can use for verification of a possible fix?

**Comment by dstenger** [comment]
Can you provide a service we can use for testing?

**Comment by dstenger** [comment]
We were able to test the fix successfully.
Pull request was created (#28) and will be merged right before the next release is built.

**Comment by dstenger** [comment]
The feature branch was tested successfully and was merged into master branch.
The fix will be part of the upcoming release.
