### ISSUE TITLE
wcs:DescribeCoverage_Response_InterpolationMethods test is faulty

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ets-wcs11#29]
The wcs:DescribeCoverage_Response_InterpolationMethods test on a WCS server with two coverages A and B sends a DescribeCoverage request with identifiers=A,B, (note the trailing comma).  According to the list-parsing rules of OWS Common 1.1.0 (OGC 06-121r3) section 11.5.3, this is clearly a three-item list where the third item is an empty string.

This happens, for example, when testing "https://demo.cubewerx.com/cubewerx/cubeserv/cite_wcs111?DATASTORE=Foundation&SERVICE=WCS&REQUEST=GetCapabilities&VERSION=1.1.1".  The server gets sent the following request:

https://demo.cubewerx.com/cubewerx/cubeserv/cite_wcs111?DATASTORE=Foundation&&service=WCS&request=DescribeCoverage&version=1.1.1&identifiers=etopo2,gtopo30,

which causes an exception report rightly stating that coverage "" doesn't exist.

**Comment by pomakis** [comment]
This is also the case for the wcs:DescribeCoverage_Response_Identifier_XML, wcs:DescribeCoverage_Response_SupportedFormat and wcs:DescribeCoverage_Response_FieldIdentifier_XML tests.

**Comment by dstenger** [comment]
Yes, that is correct. The test suite expects at least three coverages for the listed tests.

So, this should be added to the preconditions described on following page: http://cite.opengeospatial.org/teamengine/about/wcs/1.1.1/site/

Also, it should be checked whether the third coverage is really mandatory for listed tests. If this is not the case, the tests should be improved and the precondition is that two coverages exist in the service.

**Comment by dstenger** [comment]
We will do further investigation.

**Comment by lgoltz** [comment]
The following six tests should be concerned:
 * wcs:DescribeCoverage_Response_InterpolationMethods
 * wcs:DescribeCoverage_Response_Identifier_XML
 * wcs:DescribeCoverage_Response_SupportedFormat_XML
 * wcs:DescribeCoverage_Response_FieldIdentifier_XML
 * wcs:DescribeCoverage_Response_InterpolationMethod_XML
 * wcs:DescribeCoverage_Response_AxisIdentifier_XML
 * wcs:DescribeCoverage_Response_AxisKey_XML

All of them are calling the function _wcs:describe-coverage-multiple-identifiers_. I don't find any reason why exactly three identifiers should be used. I propose to limit the number of required identifiers to two. If three identifier are available they are used. If the service provides four or more identifiers only three of them (the first three in the capabilities) are used. If only one identifier is available the test is skipped (or fails).

**Comment by dstenger** [comment]
Decision: Fix will be implemented as described above.

**Comment by dstenger** [comment]
Issue was solved as described above and pull request was created: #33
Pull request will be merged into master branch as soon as testing will be finished successfully.

**Comment by dstenger** [comment]
Was was tested succesfully, merged into master branch and will be part of the next release.
