### ISSUE TITLE
WCS 1.1.1 tests make requests with double ampersands

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ets-wcs11#30]
The OWS Common specification (OGC 06-121r3) section 11.2 states that "an Online Resource URL intended for HTTP GET requests is in fact only a URL prefix" and furthermore that "an HTTP GET URL prefix always ends in either a question mark '?' or an ampersand '&'.  However, the WCS 1.1.1 CITE tests don't seem to expect this, since it blindly adds an ampersand even if the prefix already ends in one.

For example, "https://demo.cubewerx.com/cubewerx/cubeserv/cite_wcs111?DATASTORE=Foundation&SERVICE=WCS&REQUEST=GetCapabilities&VERSION=1.1.1" advertises the following HTTP GET URL prefix:

https://demo.cubewerx.com/cubewerx/cubeserv/cite_wcs111?DATASTORE=Foundation&

The CITE tests respond by making requests like the following:

https://demo.cubewerx.com/cubewerx/cubeserv/cite_wcs111?DATASTORE=Foundation&&service=WCS&request=GetCapabilities&version=1.1.1

(Note the double ampersand.)  I'm not even sure if this is valid HTTP(s) URL syntax.

**Comment by dstenger** [comment]
This issue is related to https://github.com/opengeospatial/ets-wms13/issues/41

**Comment by lgoltz** [comment]
@pomakis Is your service able to handle the double ampersand? 

I think we can close this ticket (as discussed in https://github.com/opengeospatial/ets-wms13/issues/41) if the service can handle this.

**Comment by dstenger** [comment]
@pomakis Is there any update regarding the reported behaviour?
