### ISSUE TITLE
wcs:DescribeCoverage_MissingVersion test is faulty

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ets-wcs11#31]
The wcs:DescribeCoverage_MissingVersion test verifies that when a DescribeCoverage request with a missing version parameter is submitted, the response is valid XML that validates against the OWS Common 1.1.0 ExceptionReport schema.  However, if the request doesn't indicate a version number, how is the server supposed to know what version of the WCS is being invoked, and therefore what type of exception report to return?  Pragmatically, in this situation it's the *client* that's faulty for neglecting to send a version parameter when it's required to.  It's just as bad as not sending a service parameter, for without a service/version tuple, the server has no way of knowing what specifications to comply to.

For example, the server at https://onestop.cubewerx.com/cubewerx/cubeserv/cite_wcs?DATASTORE=Foundation&service=WCS&request=GetCapabilities&VERSION=1.1.1 fails this test because it supports multiple WCS versions, and in the absence of a version parameter decides to comply with the latest official WCS version (2.0.1) when generating its exception report complaining about the missing parameter.  This happens to be an OWS Common 2.0 exception report, which fails the test.

**Comment by dstenger** [comment]
Thank you for reporting the issue.

Do you agree that issue #20 discusses the same problem except that a different test is targeted?

**Comment by pomakis** [comment]
Yes, it's the same problem in the sense that the server can't be expected to respond with an exception report of a specific version if the client doesn't indicate a version number in the request.

**Comment by dstenger** [comment]
Decision: The test is modified so that it passes with both ExceptionReport versions.

**Comment by dstenger** [comment]
Issue was fixed and pull request created: #32.
Fix will be part of the next release if all functional tests are successful.

**Comment by dstenger** [comment]
Was was tested succesfully, merged into master branch and will be part of the next release.
