### ISSUE TITLE
unable to execute wcs 1.1.1 compliance test

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wcs11#36]
Sample 1.1.1 wcs on my server:
https://ogc.webgistesting.net/server/services/wcs111/ImageServer/WCSServer?request=GetCapabilities&service=WCS&version=1.1.1

When running it against team engine production harness, I get this:
![image](https://user-images.githubusercontent.com/11200872/34899581-ad4be078-f7ae-11e7-9e55-5c88e98c461b.png)

the very first failure is to test getcapabilities request, it returns:
Test wcs:GetCapabilities_MinimalRequest type Mandatory default result Passed (s0058/d1e356_1/d1e679_1)

Assertion: Verify that when a GetCapabilities request with only mandatory
           parameters is submitted, the response is valid XML that validates
           against the WCS 1.1.1 GetCapabilities schema.

Message d1e2820_1:
   Using KVP encoding.

Request d1e2844_1:
   Method: GET
   URL: service=WCS&request=GetCapabilities&version=1.1.1
Error in call to extension function {public org.w3c.dom.NodeList com.occamlab.te.TECore.request(org.w3c.dom.Document,java.lang.String) throws java.lang.Throwable}: Exception in extension function java.net.MalformedURLException: no protocol: ?service=WCS&request=GetCapabilities&version=1.1.1
Result: Failed

The URL in log looks like having problems. My service should be good... at least for the getCapabilities request.

Original issue is https://github.com/opengeospatial/teamengine/issues/306

**Comment by lgoltz** [comment]
@greatzzk Please check your capabilities. The target namespace of the WCS 1.1.1 schema is http://www.opengis.net/wcs/1.1. That's why you have to set the default  namespace to this namespace,  not http://www.opengis.net/wcs/1.1.1 as in you capabilities.

That should be the reason why the URL as well as other detail cannot be parsed from the capabilities as you can see in the test details of `wcs:GetCapabilities-main`.

**Comment by lgoltz** [comment]
@lgoltz , thanks for the reply.
We referred to doc: 07-067r2_Web_Coverage_Service_WCS_version_1.1.1.pdf when doing the development.
There is an getCapabilities operation example at page 20, section 8.4:
![image](https://user-images.githubusercontent.com/11200872/35069928-7d50f71a-fb90-11e7-90d2-62ecaa9499b9.png)
According to the picture above, it uses http://www.opengis.net/wcs/1.1.1 rather than http://www.opengis.net/wcs/1.1

(https://github.com/opengeospatial/teamengine/issues/306#issuecomment-358466186)

**Comment by bermud** [comment]
If you look here: http://schemas.opengis.net/wcs/, the schema for 1.1.1 is available at wcs-1_1_x.zip; however, I see is not listed as an unzipped folder.

**Comment by lgoltz** [comment]
I think http://schemas.opengis.net/wcs/1.1/ contains the latest version zipped in http://schemas.opengis.net/wcs/wcs-1_1_x.zip. targetNamespace is still http://www.opengis.net/wcs/1.1

**Comment by bermud** [comment]
@Igoltz, The document "Policy Directives for Writing and Publishing OGC Standards: [TC Decisions" OGC 06-135r11 section 13.5](http://portal.opengeospatial.org/files/?artifact_id=40077 ) provides the correct guidance, when trying to get the latest schemas for 1.1 and the structure of the schemas at OGC. But it doesn't says what happens when you want to validate a 1.1.1 implementation. I think the 1.1.1 implementation needs to be validated against the schemas 1.1.1  located in the zip file (but not 1.1). 

Where dose it says that the target schema for 1.1.1 is 1.1? 

Do you know how other implementations deal with this issue e.g. GeoServer?

**Comment by lgoltz** [comment]
In  section `13.3.2 Version designator` of the  [Policy Directives for Writing and Publishing OGC Standards](http://portal.opengeospatial.org/files/?artifact_id=40077) I can find the following hint:

```
A bug fix revision corrects but does not change the meaning of, or add any new
functionality to an OGC standard or implementation of that standard. The bug fix version
designator SHALL NOT appear in the XML namespace.
```

A 1.1.1 implementation should be validated against the 1.1.1 schemas. As 1.1.1 is a bug fix version of 1.1.0 also the validation of a 1.1.0 implementation against the 1.1.1 schemas should be fine. 

http://schemas.opengis.net/wcs/wcs-1_1_x.zip contains the schemas for 1.1.1 with the namespace  http://schemas.opengis.net/wcs/1.1.1/, furthermore there is a corrigendum  1.1.3 where the namespace is reset to http://schemas.opengis.net/wcs/1.1/. 
The ETS can handle both, so the namespace binding is not the problem here. 

@greatzzk Could you make the service available for testing again?

**Comment by greatzzk** [comment]
@lgoltz , i have the service at hand right now. I just tested against "te2", which is still not working. where else can i check it?

**Comment by lgoltz** [comment]
@greatzzk There are no any fixes yet. We still make some investigations. Can you make the service (https://ogc.webgistesting.net/server/services/wcs111/ImageServer/WCSServer?request=GetCapabilities&service=WCS&version=1.1.1) available for us?

**Comment by greatzzk** [comment]
@lgoltz, I can definitely share the service with you. Due to security reasons, I have to limit the IP address that would like to visit the server. Can you pin me your IP address so that I can add to my white list? (my email: zzhou@esri.com)

**Comment by lgoltz** [comment]
The service returns an empty Capabilities document if the request contains `sections=OperationsMetadata,Contents`. The URL used for the further request cannot be parsed and the following test fails, too. 

WCS 1.1.1 Table 1 — Implementation of parameters in GetCapabilities operation request: 
```
When this parameter is not implemented or not received, server shall provide the specified 
default response. When implemented and received, server shall provide specified response.
```

I assume "the specified default response" contains all sections.  (Must be rechecked!)

Request send in test `wcs:GetCapabilities-main`: http://HOST:PORT/service?request=GetCapabilities&service=WCS&service=WCS&request=GetCapabilities&version=1.1.1&sections=OperationsMetadata,Contents&acceptversions=1.1.1

**Comment by greatzzk** [comment]
@lgoltz , yep. I see the problem. It is a regression. We don't have such problem in previous releases. We will fix this - two or more sections in request will return empty getcapabilities in wcs 1.1.1 server.

Can you show me all problem under our 1.1.1 server right now? Or can you point me to a server that I can test against?

Thanks.

**Comment by lgoltz** [comment]
@greatzzk If you have fixed this you can test with the official version of the [TEAM Engine](http://cite.opengeospatial.org/teamengine/). The latest release of the ETS WCS 1.1 is running there.

**Comment by greatzzk** [comment]
@lgoltz , do i have to fix this before i can get it working in the wcs 1.1.1 test suite?
it looks like irrelevant to the failure in get capablities minimum test case. here is the new result i get, which is the same as before:
![image](https://user-images.githubusercontent.com/11200872/36996580-031266c2-206c-11e8-9051-d3042f925e7a.png)
![image](https://user-images.githubusercontent.com/11200872/36996603-0e348f4e-206c-11e8-81a6-06cb60f8f0b6.png)

**Comment by lgoltz** [comment]
@greatzzk Yes it must be fixed before. Otherwise the relevant parts of the capabilities, like DCP URLs are not available.
