### ISSUE TITLE
Improve tests with multiple identifiers

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wcs11#39]
- [x] Several tests DescribeCoverage_ValidWithBogusIdentifiers expects multiple identifiers, but only the first is used: https://github.com/opengeospatial/ets-wcs11/blob/1db93f2d883e8cc4521d5c5be9bf50e93e06d01e/src/main/scripts/ctl/wcs.xml#L4454-L4517
  * Only required identifiers should be passed to the tests.
- [x] Other tests (e.g. DescribeCoverage_MultipleIdentifiers) require multiple identiifiers, but they will fail if the sut provides less than three identifiers: https://github.com/opengeospatial/ets-wcs11/blob/1db93f2d883e8cc4521d5c5be9bf50e93e06d01e/src/main/scripts/ctl/wcs.xml#L4265
  * Tests should be skipped if the required identifiers are not available.
  * Or the documentation must be enhanced that at least three coverages must be provided.

**Comment by keshav-nangare** [comment]
@lgoltz 

> Only required identifiers should be passed to the tests.

Removed unused identifiers from the test.

> Tests should be skipped if the required identifiers are not available.

The test `wcs:DescribeCoverage_MultipleIdentifiers` is updated now and will be skipped if required identifiers are not found.

Fixed with this PR: #42

**Comment by lgoltz** [comment]
> The test wcs:DescribeCoverage_MultipleIdentifiers is updated now and will be skipped if required identifiers are not found.

As far as I see the test is invoked if the service provides exact two coverages, but fails cause identifier3 is still used.

**Comment by keshav-nangare** [comment]
@lgoltz 

Should I remove all entries of `identifier3`?

**Comment by lgoltz** [comment]
@keshav-nangare The `identifier3` should be kept, but the test should not append it, if not available.

**Comment by keshav-nangare** [comment]
@lgoltz 

Update the test with identifier3 which will append only if it exists. Fixed with this commit: 89eb04e
