### ISSUE TITLE
New HTML report is not shown 

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wcs11#40]
Tested with https://onestop.cubewerx.com/cubewerx/cubeserv/cite_wcs?DATASTORE=Foundation&service=WCS&request=GetCapabilities&VERSION=1.1.1 on a local docker environment (TEAM Engine 5.3, 1.13-SNAPSHOT).

**Comment by keshav-nangare** [comment]
@lgoltz 

I have tested the ets-wcs11 and teamengine with above mentioned version with the docker. The new HTML report is generated. 
Here is the result:

![result](https://user-images.githubusercontent.com/14732650/50419507-1d675900-0857-11e9-887d-2cb3eae02c36.png)
