### ISSUE TITLE
Invalid KVP parameter "Identifier" in wcs:DescribeCoverage_Response_InterpolationMethods test

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ets-wcs11#51]
The wcs:DescribeCoverage_Response_InterpolationMethods test seems to sometimes leave out the comma between identifiers in its DescribeCoverage request.

This happens, for example, when testing "https://onestop.cubewerx.com/cubewerx/cubeserv/cite_wcs?DATASTORE=Foundation&service=WCS&request=GetCapabilities&VERSION=1.1.1", which has three coverages: "etopo2", "gtopo30" and "X1km177240497702008GROUPEALTA". The server gets sent the following request:

https://onestop.cubewerx.com/cubewerx/cubeserv/cite_wcs?DATASTORE=Foundation&&service=WCS&request=DescribeCoverage&version=1.1.1&identifiers=etopo2X1km177240497702008GROUPEALTA,gtopo30

which causes an exception report rightly stating that coverage "etopo2X1km177240497702008GROUPEALTA" doesn't exist.

This is also the case for the wcs:DescribeCoverage_Response_Identifier_XML, wcs:DescribeCoverage_Response_SupportedFormat and wcs:DescribeCoverage_Response_FieldIdentifier_XML tests

(This is identical to #35, which was closed as "fixed".  It doesn't seem to be fixed.  I don't seem to have the power to re-open that issue, so I re-opened it as a new one.)

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.

How/ on which environment did you execute the tests?

**Comment by pomakis** [comment]
I executed the Web Coverage Service (WCS) 1.1.1 CITE test (version 1.12) via the latest Google Chrome, and pointed it to the abovementioned URL.

**Comment by lgoltz** [comment]
@pomakis I've just rechecked on http://cite.opengeospatial.org/teamengine/ The prod environment was updated on July 19th, the test is successful now.
