### ISSUE TITLE
illegal DescribeCoverage requests sent

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ets-wcs11#55]
The WCS 1.1.1 service at
https://demo.cubewerx.com/cubewerx/cubeserv/cite_wcs111?DATASTORE=Foundation&SERVICE=WCS&REQUEST=GetCapabilities&VERSION=1.1.1
fails all of the DescribeCoverage_Response_* tests because the test suite sends the following DescribeCoverage request:

https://demo.cubewerx.com/cubewerx/cubeserv/cite_wcs111?DATASTORE=Foundation&request=DescribeCoverage&service=WCS&identifiers=etopo2,&version=1.1.1

Note the trailing comma at the end of the value of the "identifiers" parameter.  This causes the server to correctly return an exception report indicating that a coverage called "" doesn't exist.  To confuse matters a bit, the actual "reason of failure" that the test reports is:

A sequence of more than one item is not allowed as the second argument of concat()

Anyways, I suspect that the reason these tests are sending invalid requests is due to the same underlying issue as with bug #21.  I think it erroneously sees the top-level  CoverageSummary  element as a requestable coverage.  But it's not a requestable coverage because it doesn't have an identifier.  See table 5 of the WCS 1.1.1 specification (OGC 07-067r2), which indicates the following regarding the CoverageSummary Identifier element:

"Zero or one (optional); Include when this coverage is available for DescribeCoverage and GetCoverage requests"

**Comment by lgoltz** [comment]
@keshav-nangare Can you take a look at this?

**Comment by keshav-nangare** [comment]
The test is expecting two or three identifiers. We can see that there is only one identifier due to concat operation the extra comma gets appended. So we have updated test which will set an identifier according to its availability.
