### ISSUE TITLE
erroneous requirement that each CoverageSummary has an abstract

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ets-wcs11#56]
While it might be considered good practice for each CoverageSummary to have an abstract description, the WCS 1.1.0 specification by no means requires it.  Many coverages simply don't have abstract descriptions available for them, and it's totally legal to serve such coverages through a WCS.  Therefore, the test suite shouldn't fail if it encounters a coverage without an abstract description.  In other words, the GetCapabilities_Response_OperationsMetadata_Contents_CoverageSummary_Abstract test shouldn't exist.

**Comment by dstenger** [comment]
@keshav-nangare Can you please analyse this issue?

**Comment by dstenger** [comment]
Test derives from abstract test suite: https://opengeospatial.github.io/ets-wcs11/ats.html
Test: Table 33. GetCapabilities Response OperationsMetadata Contents CoverageSummary Abstract

I also do not find any hint in specification that `Abstract` is mandatory.

Thus, I propose to remove the test and to update the test suite.

**Comment by keshav-nangare** [comment]
Fixed with this commit: 7fb4ba692f9804c293b3c5a4f9a82ca07baaa1e1

**Comment by lgoltz** [comment]
PR #59 was reverted by #60

**Comment by keshav-nangare** [comment]
Service:
[1] https://demo.cubewerx.com/cubewerx/cubeserv/cite_wcs111?DATASTORE=Foundation&SERVICE=WCS&REQUEST=GetCapabilities&VERSION=1.1.1

TeamEngine Version: 5.5. SNAPSHOT

I am able to execute the test suite successfully with the above service [1]. The test `GetCapabilities_Response_OperationsMetadata_Contents_CoverageSummary_Abstract` does not exist more.
