### ISSUE TITLE
wcs 111 compliance test cannot correctly parse the time from a describecoverage call

### ISSUE THREAD

**Issue by greatzzk** [opengeospatial/ets-wcs11#64]
time period is returning like the following:
![image](https://user-images.githubusercontent.com/11200872/88857082-78d39880-d1aa-11ea-87f3-a256e7549743.png)
but a later getcoverage call is wrongly using the time like the following:
![image](https://user-images.githubusercontent.com/11200872/88857122-8c7eff00-d1aa-11ea-8836-76a821bd4cd2.png)
this is for test on te2: Test wcs:GetCoverage_TemporalSubset_TimePosition_Early (View Details): Failed
it should be using "2014-10-26T06:00:00Z" in the request

**Comment by dstenger** [comment]
Thank you for reporting.
Is there a test service available?

@keshav-nangare Can you please take a look at the reported behavior?

**Comment by greatzzk** [comment]
@dstenger @keshav-nangare 
pls try with this service. 
http://54.144.24.46:6080/arcgis/services/ndfd2/ImageServer/WCSServer?request=GetCapabilities&service=WCS
I open it for both of your IPs on my file. let me know if you cannot access it.

**Comment by keshav-nangare** [comment]
@dstenger 

According to the specification document, he is right we should update the test which will use correct value(timestamp. Below are the doc references:

> OGC 07-067r2 Subclauses10.2.1.1 Tables 21, 22 and 23; 9.3.1.2 Tables 13 and  14; and 9.3.2.4." http://www.opengeospatial.org/standards/wcs#OGC-07-067r2

![image](https://user-images.githubusercontent.com/14732650/89200747-13c6db00-d5ce-11ea-9cbb-24a6a12f652b.png)


According to sub-clause 9.3.2.4, the `TimeSequence` parameter value should be a valid timestamp(We can see the examples from below screenshot).


![image](https://user-images.githubusercontent.com/14732650/89201181-ba12e080-d5ce-11ea-975f-e539c9e59539.png)


Currently `TimeSequence` value is hardcoded in test implementation. 
https://github.com/opengeospatial/ets-wcs11/blob/06b632ac28947196835865a46c5959e1f9004fb6/src/main/scripts/ctl/GetCoverage.xml#L3625-L3639


@dstenger Can you please guide me, what exact value should we use here?

**Comment by ghobona** [comment]
As discussed 2020-08-05, the timestamp on line 3635 should be changed to a valid timestamp following the structure on page 35 of 07-067r2.

**Comment by keshav-nangare** [comment]
@dstenger @ghobona @greatzzk 

I have fixed this issue and the test will parse the timestamp from service response and passed to request.

The following tests are updated:
- wcs:GetCoverage_TemporalSubset_TimePosition_Early
- wcs:GetCoverage_TemporalSubset_TimePosition_Late

**Comment by greatzzk** [comment]
@keshav-nangare 
1. you mentioned only two tests are updated, but i am seeing a couple of more are failing with similar reasons too. are they fixed as well?
![image](https://user-images.githubusercontent.com/11200872/89584113-64b61980-d7f0-11ea-9d5c-07a6f00245ac.png)
![image](https://user-images.githubusercontent.com/11200872/89584151-70a1db80-d7f0-11ea-9f8c-7b6a152345c4.png)
2. could you push to te2 for me to verify your fix?

**Comment by keshav-nangare** [comment]
@greatzzk 

Is it a valid request if the `TimeSequence` parameter is empty?

Test name: `wcs:GetCoverage_TemporalSubset_TimePosition`
Request:
http://ec2-54-144-24-46.compute-1.amazonaws.com:6080/arcgis/services/ndfd2/ImageServer/WCSServer?service=WCS&request=GetCoverage&version=1.1.1&identifier=ndfd&BoundingBox=0,0,3035,1832,urn:ogc:def:crs:OGC::imageCRS&TimeSequence=&Format=image/GeoTIFF

**Comment by greatzzk** [comment]
@keshav-nangare 
yes. it will be just ignored by server, which means there is no TimeSequence - and it is an optional parameter.
reference:
![image](https://user-images.githubusercontent.com/11200872/90046250-12a84480-dc85-11ea-8938-b3165d7e230b.png)

**Comment by keshav-nangare** [comment]
@dstenger @ghobona 

I have referred the schema and the response received by DescribeCoverage request seems to be correct according to schema documentation. 
https://github.com/opengeospatial/ets-wcs11/blob/06b632ac28947196835865a46c5959e1f9004fb6/src/main/resources/xsd/ogc/wcs/1.1.1/wcsCommon.xsd#L50-L71

According to the schema, we have to update the XPath for the following tests:
1. wcs:GetCoverage_TemporalSubset_TimePosition
2. wcs:GetCoverage_TemporalSubset_TimePeriod
3. wcs:GetCoverage_TemporalSubset_TimePeriod_With_Resolution
4. wcs:GetCoverage_TemporalSubset_TimePeriod_With_Resolution_And_Frame
5. wcs:GetCoverage_TemporalSubset_TimePeriod_BeginTime_Only
6. wcs:GetCoverage_TemporalSubset_TimePeriod_EndTime_Only

They are currently using `/*TemporalDomain/TimePositionOrInterval/TimePosition` XPath which return empty value and according to schema it should be  `/*TemporalDomain/TimePeriod/BeginPosition`.

**Comment by greatzzk** [comment]
@keshav-nangare thanks, let me know if i could use te2 to try out your new fix.

**Comment by keshav-nangare** [comment]
@dstenger 

I have updated XPath for tests mentioned in an earlier comment. Please find changes in the same PR.

**Comment by dstenger** [comment]
@greatzzk We will update the Beta environment (https://cite.opengeospatial.org/te2/) next week and the update will contain the fix for this issue.
