### ISSUE TITLE
Regression: Several tests fail as syntax for RangeSubset is erroneous

### ISSUE THREAD

**Issue by greatzzk** [opengeospatial/ets-wcs11#65]
It looks like the problem described in the following issue is bounced back: https://github.com/opengeospatial/ets-wcs11/issues/26

To reproduce, just throw this wcs in te2 for running against wcs1.1.1 compliance test and watch out for:
Test wcs:GetCoverage_RangeSubset_Identifier (View Details): Failed

`http://54.144.24.46:6080/arcgis/services/ndfd2/ImageServer/WCSServer?request=GetCapabilities&service=WCS&acceptversions=1.1.1`

**Comment by dstenger** [comment]
@keshav-nangare Can you please take a look at the reported behavior?

**Comment by greatzzk** [comment]
@keshav-nangare 
have you reproduced this issue? do you still need the service? I am going to update the server's build, so it will be offline for a while.

**Comment by keshav-nangare** [comment]
Fix with #67 PR.

**Comment by greatzzk** [comment]
@keshav-nangare thanks, let me know if i could use te2 to try out your new fix.

**Comment by dstenger** [comment]
@greatzzk We will update the Beta environment (https://cite.opengeospatial.org/te2/) next week and the update will contain the fix for this issue.
