### ISSUE TITLE
Error - cannot find declaration of element Capabilities

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wcs11#7]
![screen shot 2014-11-19 at 9 29 10 am](https://cloud.githubusercontent.com/assets/3738898/5107301/94ca7ad4-6fce-11e4-87cb-606d36135c23.png)

Testing details:
- http://ows.eox.at/cite-wcs?service=wcs&version=1.1.1&request=getcapabilities
- commit: cc7fae5eea50a59ecd78a4ef27433d39892070ea  (r2-SNAPSHOT)

---

Testing suite wcs:suite in Test Mode with defaultResult of Pass ...

Testing wcs:Main type Mandatory in Test Mode with defaultResult Pass (s0034)...

      Assertion: The Implementation Under Test (IUT) satisfies all applicable

                  assertions. There are 177 tests in total. Depending on the capabilities

                       of the server, some tests are skipped. These are recorded in the

                      detailed results for each type of request.

      WCS 1.1.1 URL is http://ows.eox.at/cite-wcs?service=wcs&version=1.1.1&request=getcapabilities.

Testing wcs:GetCapabilities-main type Mandatory in Test Mode with defaultResult Pass (s0034/d1e329_1)...

         Assertion: All assertions for "GetCapabilities" conformance are satisfied.

Validation error:

  cvc-elt.1.a: Cannot find the declaration of element 'Capabilities'.

1 validation error detected.

         

         The service metadata document has version  but expected to find 1.1.1 as the highest protocol supported. See OGC 06-121r3 subclause 7.3.2.

         

         The server seems to have a problem with handling the GetCapabilities sections parameter. No tests will be performed.

         The EqualUpdateSequence value is .

         The URL for KVP encoding is .

         The URL for XML encoding is .

         XML encoding is not supported.

         sections-supported: false.

      Test wcs:GetCapabilities-main Failed

Testing wcs:DescribeCoverage-main type Mandatory in Test Mode with defaultResult Pass (s0034/d1e334_1)...

         Assertion: All assertions for "DescribeCoverage" conformance are satisfied.

Validation error:

  cvc-elt.1.a: Cannot find the declaration of element 'Capabilities'.

1 validation error detected.

         

         The service metadata document has version  but expected to find 1.1.1 as the highest protocol supported. See OGC 06-121r3 subclause 7.3.2.

         

         The server seems to have a problem with handling the GetCapabilities sections parameter. No tests will be performed.

         The URL for KVP encoding is .

         The URL for XML encoding is .

         XML encoding is not supported.

         Identifier1 is .

         Identifier2 is .

         Identifier3 is .

      Test wcs:DescribeCoverage-main Failed

Testing wcs:GetCoverage-main type Mandatory in Test Mode with defaultResult Pass (s0034/d1e339_1)...

         Assertion: All assertions for "GetCoverage" conformance are satisfied.

Validation error:

  cvc-elt.1.a: Cannot find the declaration of element 'Capabilities'.

1 validation error detected.

         

         The service metadata document has version  but expected to find 1.1.1 as the highest protocol supported. See OGC 06-121r3 subclause 7.3.2.

         

         The server seems to have a problem with handling the GetCapabilities sections parameter. No tests will be performed.

         The URL for KVP encoding is .

         The URL for XML encoding is .

         XML encoding is not supported.

Is not passing
         store supported is false.

         Identifier1 is .

         Identifier2 is .

         Identifier3 is .

      Test wcs:GetCoverage-main Failed

   Test wcs:Main Failed

Suite wcs:suite Failed

**Comment by bermud** [comment]
I'm reopening this issue. 
Some implementations passed with the WCS 1.1.1 schemas.
The fix for this issue replaced the schemas with 1.1.3 schemas, but it seems that there is no backwards compatibility with 1.1.1.

I suggest we edit the test to allow implementations to test for 1.1.1 or 1.1.3.

Both schemas are here: http://schemas.opengis.net/wcs/wcs-1_1_x.zip

**Comment by dstenger** [comment]
We created a fix, so that both schemas are supported in schema validation, now: https://github.com/opengeospatial/ets-wcs11/pull/12

**Comment by dstenger** [comment]
The pull request was merged and the fix will be part of the next release.
