### ISSUE TITLE
WCS 1.1.1 DescribeCoverage_MinimalRequest test has problem

### ISSUE THREAD

**Issue by greatzzk** [opengeospatial/ets-wcs11#70]
sample service:
http://54.160.203.226:6080/arcgis/services/mynetcdf/ImageServer/WCSServer?&request=DescribeCoverage&service=WCS&identifiers=mynetcdf&version=1.1.1
let me know if testing service is inaccessible.

My service fails in this test. The log says:
```
Request d22326e1295_1:
   Method: GET
   URL: http://54.160.203.226:6080/arcgis/services/mynetcdf/ImageServer/WCSServer?service=WCS&request=DescribeCoverage&version=1.1.1&identifiers=mynetcdf
   Response from parser ctlp:XMLValidatingParser:
      
   Messages from parser ctlp:XMLValidatingParser:
        Validation error:
  cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.opengis.net/wcs/1.1.1":ValuesUnit}'. One of '{"http://www.opengis.net/ows/1.1":Title, "http://www.opengis.net/ows/1.1":Abstract, "http://www.opengis.net/ows/1.1":Keywords, "http://www.opengis.net/wcs/1.1.1":AvailableKeys}' is expected.
```

My service has a <UOM> element inside the <ValuesUnit> element. I think this is a valid element according to spec. It should use <UOM> and <ReferenceSystem> inside the <ValuesUnit>. But it looks like the test is checking some other incorrect elements.
reference: 07-067r2 page 30
![image](https://user-images.githubusercontent.com/11200872/108769531-f3c91b80-750d-11eb-87e3-c790b9aeaf38.png)

**Comment by ghobona** [comment]
@greatzzk 

I have just reviewed the DescribeCoverage response and noticed that it is missing a namespace declaration.

Here is the first issue I found.

The root element is presented as:

```xml
<CoverageDescriptions xmlns:ows="http://www.opengis.net/ows/1.1"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:schemaLocation="http://www.opengis.net/wcs/1.1 http://schemas.opengis.net/wcs/1.1/wcsDescribeCoverage.xsd http://www.opengis.net/ows/1.1/ http://schemas.opengis.net/ows/1.1.0/owsAll.xsd">
```

Notice that the default namespace to which `CoverageDescriptions` belongs is missing. So you need to declare the default namespace of `xmlns="http://www.opengis.net/wcs/1.1" ` so that the parser know where `CoverageDescriptions` belongs.

**Comment by ghobona** [comment]
The second issue is that `ValuesUnit` has been instantiated. The [schema](http://schemas.opengis.net/ows/1.1.0/owsDomainType.xsd) specifies `ValuesUnit` as a group, which means that it is not meant to be instantiated. Instead, it is the elements within the group that can be instantiated.

Please remember to also specify the namespace prefix.

So instead of `<ValuesUnit><UOM>Meters</UOM><ValuesUnit>`, it should be `<ows:UOM>ISO8601</ows:UOM>`.

**Comment by ghobona** [comment]
The third issue is the positioning of the `UOM` and other elements from the `ValuesUnit` group. 

The sequence of the elements is important and it is always top down.

The [schema](http://schemas.opengis.net/wcs/1.1/wcsDescribeCoverage.xsd) shows the `AvailableKeys` element appearing before `ValuesUnit`. Therefore, when instantiated `AvailableKeys` should appear above any elements from the `ValuesUnit` group. For example, the correct sequence should be in the CoverageDescription would be:

```xml
                        <Axis identifier="StdTime">                            
                           <AvailableKeys>
                              <Key>2013-03-17T00:00:00          </Key>
                              <Key>2013-03-17T03:00:00          </Key>
                              <Key>2013-03-17T06:00:00          </Key>
                              <Key>2013-03-17T09:00:00          </Key>
                              <Key>2013-03-17T12:00:00          </Key>
                              <Key>2013-03-17T15:00:00          </Key>
                              <Key>2013-03-17T18:00:00          </Key>
                              <Key>2013-03-17T21:00:00          </Key>
                           </AvailableKeys>    
                            <ows:UOM>ISO8601</ows:UOM>                                                          
                        </Axis>
```

**Comment by ghobona** [comment]
The original and fixed responses are attached.

[describeCoverageResponse.zip](https://github.com/opengeospatial/ets-wcs11/files/6028537/describeCoverageResponse.zip)

**Comment by keshav-nangare** [comment]
@greatzzk 

The service is inaccessible.

**Comment by ghobona** [comment]
@greatzzk Please fix the issues in my previous comments and then let us know if the Validation error is addressed.

**Comment by greatzzk** [comment]
@ghobona 
We updated our server based on your direction, these failed tests are green now. thanks. 
closing this issue
