### ISSUE TITLE
GetCoverage_TemporalSubset_TimePeriod_With_Resolution has problem

### ISSUE THREAD

**Issue by greatzzk** [opengeospatial/ets-wcs11#72]
The test is to verify that when a GetCoverage request with a TimePeriod with resolution is submitted, the response is not an exception.

In my test, after describe coverage, it is making get coverage with the following request:
http://myserver:6080/arcgis/services/mynetcdf_111/ImageServer/WCSServer?&request=GetCoverage&identifier=mynetcdf&Format=image/GeoTIFF&service=WCS&BoundingBox=0,0,400,611,urn:ogc:def:crs:OGC::imageCRS&TimeSequence=2013-1-17T00:00:00Z/2013-5-17T00:00:00Z/P1D&version=1.1.1

The problem is at Time Sequence parameter. The parameter the test sends doesn't follow iso8601 time spec.
Instead of using 2013-1-17T00:00:00Z/2013-5-17T00:00:00Z/P1D, it should be using 2013-01-17T00:00:00Z/2013-05-17T00:00:00Z/P1D

**Comment by dstenger** [comment]
Thank you for reporting.

I agree with your conclusion that the time format should be as defined in specification OGC 07-067r2:

```
9.3.2.4 Summary of ISO 8601 syntax for time positions and time periods
The [ISO 8601:2000] syntax for dates and times may be summarized by the following
template (see Annex D of the OGC Web Map Service [OGC 06-042]):
ccyy-mm-ddThh:mm:ss.sssZ
...
The WCS GetCoverage KVP syntax (defined in 10.2.2) extends ISO 8601:2000 with a
syntax for time lists and ranges, as specified in Annex D of [OGC 06-042]. Some examples
follow:
EXAMPLE 7 2000-06-23T20:07:48.11Z (A single moment)
EXAMPLE 8 1999-01-01,1999-04-01,1999-07-01,1999-10-01 (A list of four dates)
EXAMPLE 9 1995-04-22T12:00Z/2000-06-21T12:00Z/P1D
(Daily (“P1D”) between 12 noon on April 22 1995 and 12 noon on June 21, 2000)
```

However, the test retrieves the value of `TimeSequence` from a DescribeCoverage request.

Code:

https://github.com/opengeospatial/ets-wcs11/blob/9af484963980c57a33d188ef4c46003d9eb91fee/src/main/scripts/ctl/GetCoverage.xml#L4095

https://github.com/opengeospatial/ets-wcs11/blob/9af484963980c57a33d188ef4c46003d9eb91fee/src/main/scripts/ctl/GetCoverage.xml#L4120

@greatzzk Unfortunately, I cannot access your test service but I assume that it returns an invalid time format in element BeginPosition (please check XPath in referenced code) when requested via DescribeCoverage.
Can you please check this?

**Comment by greatzzk** [comment]
@dstenger thank you!
I will send you an email for accessing the testing service, but i hope the screenshot at the bottom explains it, in which describe coverage results have correct time format.
By looking at your code, it looks like it involves some numeric calculations, That part is very suspicious that could have trimmed the "0" in front of a month numer
![image](https://user-images.githubusercontent.com/11200872/173121927-c7cda008-e79a-4e57-8ce8-64c775fe9c69.png)

**Comment by ghobona** [comment]
@greatzzk Is this issue still occurring?

**Comment by greatzzk** [comment]
@ghobona are you able to reproduce the problem with my service?

**Comment by dstenger** [comment]
@greatzzk Thank you for providing the endpoint. Yes, we are able to reproduce the problem.

**Comment by greatzzk** [comment]
can this be deployed to te2 so that i can verify the issue?

**Comment by dstenger** [comment]
@greatzzk We will create a new Beta release within coming week (by October 31). An announcement will be sent to the cite-forum mailing list.
