### ISSUE TITLE
` FieldSubset / InterpolationMethod` locator tests

### ISSUE THREAD

**Issue by davidblasby** [opengeospatial/ets-wcs11#76]
**Describe the bug**

There are a few tests that check that the `locator` attribute in a ServiceException **contains** ` FieldSubset / InterpolationMethod`.  

For example;
https://github.com/opengeospatial/ets-wcs11/blob/master/src/main/scripts/ctl/GetCoverage.xml#L5586

I find it strange that its looking for `[space]FieldSubset[space]/[space]InterpolationMethod`, which seems to very specific with the leading [space] and spaces between the "/".  The test is also **contains**, which implies there should be more.

I tried looking through the specification, but wasn't able to find what it should be.

It looks like the test is trying to match some specific text.  What text is this and where did it come from?

There is a small amount of discussing of this here;
https://github.com/geoserver/geoserver/pull/6428
(which is a Geoserver PR to pass these tests)

Summary:
I think this `locator` is incorrect.  Perhaps the test should just be looking for an exception?  Is there guidance in the specification?

Thanks a lot!

**Comment by aaime** [comment]
In my personal experience, locator normally refers to the KVP key that holds the parameter at hand.

**Comment by dstenger** [comment]
Thank you for reporting. I also checked the [specification](https://portal.ogc.org/files/07-067r2) and did not find a clear answer for your request.
Table 28 explains the usage of locator values for GetCoverage operations and following values are possible:
* **MissingParameterValue** | Operation request does not include a parameter value, and this server did not declare a default value for that parameter | **_Name of missing parameter_**
* **InvalidParameterValue** | Operation request contains an invalid parameter value | **_Name of parameter with invalid value_**
* **UnsupportedCombination** | Operation request contains an output CRS that can not be used within the output format. | **_Name of Format or name of CRS_**

It seems like a good explanation that _FieldSubset_ should be the value of locator as this is the actual parameter containing an invalid value.

We will discuss this issue in the CITE team.

**Comment by davidblasby** [comment]
Thank you very much!

**Comment by davidblasby** [comment]
NOTE: I think there are a several tests that check for `FieldSubset / InterpolationMethod` in the locator.

**Comment by dstenger** [comment]
@pebau @Schpidi
The CITE test currently expects the following: When a GetCoverage request with a missing InterpolationMethod is submitted, the response contains an exception with locator " FieldSubset / InterpolationMethod".
We checked table 28 of [specification](https://portal.ogc.org/files/07-067r2) which states that the name of parameter with invalid value should be the value of the locator. This would be "RangeSubset" in this case.
What are your thoughts about this? Do you know a reason why the value of the locator should be " FieldSubset / InterpolationMethod"?

**Comment by dstenger** [comment]
@davidblasby Is it possible to provide a demo/test endpoint we can use to reproduce your problem?

**Comment by pebau** [comment]
what exactly is "missing InterpolationMethod" - (a) missing key, or (b) key with missing value? For (a), the server-side default should kick in IMHO. For (b), it should be a syntax error actually.

Anyway, this is WCS 1.1 which is deprecated since long; only a few people are alive that have contributed to the spec, and they have bad memory ;-) ...in other words: I do no recall what was meant there.

**Comment by davidblasby** [comment]
I agree with @aaime  and @dstenger - it should be "rangeSubset".  I don't know the reason it should have been " FieldSubset / InterpolationMethod" - especially with the weird spaces (and using contains instead of equals).  
I think this was a mistake - perhaps trying to match a specific implementation's error message??????

I've been testing locally (localhost) - however there is a demo geoserver (older version) at https://how2map.geocat.live/geoserver/ows 

NOTE: I think there are 2 tests that use " FieldSubset / InterpolationMethod"

**Comment by dstenger** [comment]
The specification is not 100% clear about this case. Thus, we propose to remove the check on the locator and just verify if an Exception inside an ExceptionReport is returned.

**Comment by davidblasby** [comment]
sounds great!

**Comment by davidblasby** [comment]
PR for this - https://github.com/opengeospatial/ets-wcs11/pull/77

**Comment by dstenger** [comment]
Solved by #77.
