### ISSUE TITLE
WCS 1.1.1 compliance test on describecoverage has problem in verifying possibleValues element

### ISSUE THREAD

**Issue by greatzzk** [opengeospatial/ets-wcs11#78]
![image](https://github.com/opengeospatial/ets-wcs11/assets/11200872/1105cde8-2873-4fec-b4d8-96c5110f9990)
the errors are similar. they are saying:

> Validation error:
>   cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.opengis.net/wcs/1.1":PossibleValues}'. One of '{"http://www.opengis.net/ows/1.1":AllowedValues, "http://www.opengis.net/ows/1.1":AnyValue, "http://www.opengis.net/ows/1.1":NoValues, "http://www.opengis.net/ows/1.1":ValuesReference}' is expected.

my server has an implementation like the following picture:
![image](https://github.com/opengeospatial/ets-wcs11/assets/11200872/1a3c9ff4-5104-44ec-bc08-9bfce53624b9)

I think the test has the incorrect implementation, reasons:
in 07-067r2, table 17:
![image](https://github.com/opengeospatial/ets-wcs11/assets/11200872/9c96dbed-21d2-4420-a6f7-4afbf92113c9)
in 06-121r3, figure 16:
![image](https://github.com/opengeospatial/ets-wcs11/assets/11200872/fc4b8742-fc88-41df-8ef2-6fae4cac631d)

**Comment by dstenger** [comment]
Thank you for reporting.

It seems that `AllowedValues` is expected in `http://www.opengis.net/ows/1.1` namespace. However, your service is using `http://www.opengis.net/wcs/1.1` namespace.
Can you please check this?

**Comment by greatzzk** [comment]
http://54.90.187.123:6080/arcgis/services/mynetcdf_111/ImageServer/WCSServer?request=describecoverage&version=1.1.1&identifiers=mynetcdf&service=WCS

@dstenger i am a bit confused here, could you help check my service above and tell me where it should be changed? It looks like I also have the http://www.opengis.net/ows/1.1 namespace in the description

**Comment by dstenger** [comment]
Please check https://schemas.opengis.net/wcs/1.1/wcsDescribeCoverage.xsd.
Here you can see that Definition is of type `ows:UnNamedDomainType`:
```
...
					<element name="Definition" type="ows:UnNamedDomainType">
						<annotation>
							<documentation>Further definition of this field, including meaning, units, etc. In this Definition, the AllowedValues should be used to encode the extent of possible values for this field, excluding the Null Value. If the range is not known, AnyValue should be used. </documentation>
						</annotation>
					</element>
...
```

`ows:UnNamedDomainType` is defined in https://schemas.opengis.net/ows/1.1.0/owsDomainType.xsd describing that the elements have to be bound to `http://www.opengis.net/ows/1.1` namespace:
```
...
	<complexType name="UnNamedDomainType">
		<annotation>
			<documentation>Valid domain (or allowed set of values) of one quantity, with needed metadata but without a quantity name or identifier. </documentation>
		</annotation>
		<sequence>
			<group ref="ows:PossibleValues"/>
			<element ref="ows:DefaultValue" minOccurs="0">
				<annotation>
					<documentation>Optional default value for this quantity, which should be included when this quantity has a default value. </documentation>
				</annotation>
			</element>
			<element ref="ows:Meaning" minOccurs="0">
				<annotation>
					<documentation>Meaning metadata should be referenced or included for each quantity. </documentation>
				</annotation>
			</element>
			<element ref="ows:DataType" minOccurs="0">
				<annotation>
					<documentation>This data type metadata should be referenced or included for each quantity. </documentation>
				</annotation>
			</element>
			<group ref="ows:ValuesUnit" minOccurs="0">
				<annotation>
					<documentation>Unit of measure, which should be included when this set of PossibleValues has units or a more complete reference system. </documentation>
				</annotation>
			</group>
			<element ref="ows:Metadata" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional unordered list of other metadata about this quantity. A list of required and optional other metadata elements for this quantity should be specified in the Implementation Specification for this service. </documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- ========================================================== -->
	<group name="PossibleValues">
		<annotation>
			<documentation>Specifies the possible values of this quantity. </documentation>
		</annotation>
			<choice>
				<element ref="ows:AllowedValues"/>
				<element ref="ows:AnyValue"/>
				<element ref="ows:NoValues"/>
				<element ref="ows:ValuesReference"/>
			</choice>
	</group>
...
```

**Comment by greatzzk** [comment]
@dstenger thanks for your last reply and sorry for not being able to get back to in time.

our current implementation: 
e.g.
```
<Definition>
  <PossibleValues>
    <AllowedValues>
      <Range>
        <MinimumValue>24.006001</MinimumValue>
        <MaximumValue>35.372002</MaximumValue>
      </Range>
    </AllowedValues>
  </PossibleValues>
</Definition>
```
just to confirm: are you saying we should update this section to:
```
<Definition>
  <ows:PossibleValues>
    <ows:AllowedValues>
      <ows:Range>
        <ows:MinimumValue>24.006001</ows:MinimumValue>
        <ows:MaximumValue>35.372002</ows:MaximumValue>
      </ows:Range>
    </ows:AllowedValues>
  </ows:PossibleValues>
</Definition>
```

**Comment by dstenger** [comment]
@greatzzk Yes, I agree, this is a valid structure.

**Comment by greatzzk** [comment]
@dstenger 
I am reopening this issue as te2 still reports the same error on our updated server:
![image](https://github.com/opengeospatial/ets-wcs11/assets/11200872/fda5696a-5208-471b-b737-530b0d923d50)
we made the change according to this comment: https://github.com/opengeospatial/ets-wcs11/issues/78#issuecomment-1636594280
here is our service:
http://54.90.187.123:6080/arcgis/services/mynetcdf/ImageServer/WCSServer?service=WCS&request=DescribeCoverage&version=1.1.1&identifiers=mynetcdf

could you help take a look and advise?

**Comment by dstenger** [comment]
Thank you for reporting back.

We checked your service and following changes have to be done:
* ows:PossibleValues is a group and not an element. Thus, ows:PossibleValues must be removed so that the structure looks like this:
```
<Definition>
    <ows:AllowedValues>
      <ows:Range>
        <ows:MinimumValue>24.006001</ows:MinimumValue>
        <ows:MaximumValue>35.372002</ows:MaximumValue>
      </ows:Range>
    </ows:AllowedValues>
</Definition>
```
* Also, the Description element must be removed as it is not defined in the schema. FieldType extends the DescriptionType but the Description element itself is not part of the schema.

**Comment by greatzzk** [comment]
@dstenger for your comment on "Description element must be removed":
I found this in the reference doc and it actually comes from our user's request so we added it in lately. 
![image](https://github.com/opengeospatial/ets-wcs11/assets/11200872/5acdb67f-70f9-4883-a00c-2970611cc79a)
Do we have an alternative place to add the description for a field inside the describe coverage response?

**Comment by dstenger** [comment]
@greatzzk 
Please see following schema for details about ows:DescriptionType: https://schemas.opengis.net/ows/1.1.0/owsDataIdentification.xsd
```
...
	<complexType name="DescriptionType">
		<annotation>
			<documentation>Human-readable descriptive information for the object it is included within.
This type shall be extended if needed for specific OWS use to include additional metadata for each type of information. This type shall not be restricted for a specific OWS to change the multiplicity (or optionality) of some elements.
			If the xml:lang attribute is not included in a Title, Abstract or Keyword element, then no language is specified for that element unless specified by another means.  All Title, Abstract and Keyword elements in the same Description that share the same xml:lang attribute value represent the description of the parent object in that language. Multiple Title or Abstract elements shall not exist in the same Description with the same xml:lang attribute value unless otherwise specified. </documentation>
		</annotation>
		<sequence>
			<element ref="ows:Title" minOccurs="0" maxOccurs="unbounded"/>
			<element ref="ows:Abstract" minOccurs="0" maxOccurs="unbounded"/>
			<element ref="ows:Keywords" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
...
```

Thus, you could use ows:Abstract or ows:Keywords.
E.g.:
```
...
  <Range>
    <Field>
      <ows:Abstract>TextAbstract</ows:Abstract>
      <Identifier>textIdentifier</Identifier>
      <Definition>
        <ows:AllowedValues>
          <ows:Range>
...
```

Does this help you with your use case?

**Comment by greatzzk** [comment]
@dstenger 
thanks! we updated the implementation accordingly:
![image](https://github.com/opengeospatial/ets-wcs11/assets/11200872/1349f890-8ee0-4f7b-b457-bdcbeccbfefe)

**Comment by dstenger** [comment]
@greatzzk Did you check it against this test suite?
I think _ows:Abstract_ must be before _Identifier_ as I described in my example.

**Comment by greatzzk** [comment]
@dstenger updated server and retested against te2. our server passed all 1.1.1 tests... closing the issue
